apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ibm-dv.openshift-operators: ''
  name: {{ .Values.subscriptions.ibmdvoperator.name }}
  namespace: ibm-common-services 
spec:
  {{- toYaml .Values.subscriptions.ibmdvoperator.subscription | nindent 2 }}
