subscriptions:
  ibmdvoperator:
    name: ibm-dv-operator
    subscription:
      channel: v1.7
      installPlanApproval: Automatic
      name: ibm-dv
      source: ibm-operator-catalog
      sourceNamespace: openshift-marketplace
