apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr
  namespace: tools
spec:
  license:
    accept: true
    license: Enterprise
  storageVendor: ocs
  storageClass: ocs-storagecluster-cephfs
  zenCoreMetadbStorageClass: ocs-storagecluster-ceph-rbd
