apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr
spec:
  license:
    accept: true
    license: Enterprise
  storageClass: ocs-storagecluster-ceph-rbd
  zenCoreMetadbStorageClass: ocs-storagecluster-ceph-rbd 
  version: "4.0.1"
